// Command seed inserts a small demo catalog for local development:
// CSCI 151 → 2025 fall → Midterm 1 → one material with a generated PNG page.
//
// It is idempotent: if the demo course already exists it does nothing, so it
// is safe to run repeatedly (spec R-DX-1). It is a developer convenience, not
// production code; every query it uses is covered by the catalog tests.
package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"log/slog"
	"os"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/joho/godotenv"

	"github.com/Nurasick/NUPP/api/internal/catalog/catalogdb"
	"github.com/Nurasick/NUPP/api/internal/config"
	"github.com/Nurasick/NUPP/api/internal/db"
	"github.com/Nurasick/NUPP/api/internal/storage"
)

const demoSlug = "csci-151"

func main() {
	if err := run(context.Background()); err != nil {
		slog.Error("seed failed", "err", err)
		os.Exit(1)
	}
}

func run(ctx context.Context) error {
	if err := godotenv.Load(); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("load .env: %w", err)
	}
	cfg, err := config.Load(os.Getenv)
	if err != nil {
		return err
	}
	pool, err := db.Connect(ctx, cfg.DatabaseURL)
	if err != nil {
		return err
	}
	defer pool.Close()
	// Safe even if the server is starting at the same moment: migrations
	// take an advisory lock (R-DB-19).
	if err := db.Migrate(ctx, pool); err != nil {
		return err
	}
	files, err := storage.NewLocal(cfg.StorageDir)
	if err != nil {
		return err
	}

	if _, err := catalogdb.New(pool).GetCourseBySlug(ctx, demoSlug); err == nil {
		slog.Info("demo data already present, nothing to do")
		return nil
	} else if !errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("check existing data: %w", err)
	}

	page, err := demoPNG()
	if err != nil {
		return err
	}

	// All rows are created in one transaction: either the whole demo chain
	// exists afterwards, or none of it does.
	tx, err := pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin: %w", err)
	}
	// Rollback after a successful Commit is a harmless no-op, so deferring it
	// is the idiomatic way to guarantee cleanup on every error path.
	defer func() { _ = tx.Rollback(ctx) }()

	key, err := insertDemo(ctx, catalogdb.New(pool).WithTx(tx), page)
	if err != nil {
		return err
	}
	// Store the file before committing: if this fails, the rollback removes
	// the rows, so the database never points at a missing file.
	if err := files.Put(ctx, key, bytes.NewReader(page)); err != nil {
		return fmt.Errorf("store demo file: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit: %w", err)
	}
	slog.Info("seeded demo catalog", "course", demoSlug, "file_key", key)
	return nil
}

// insertDemo creates the demo rows and returns the storage key for the file.
func insertDemo(ctx context.Context, q *catalogdb.Queries, page []byte) (string, error) {
	dept := "SEDS"
	course, err := q.CreateCourse(ctx, catalogdb.CreateCourseParams{
		Code: "CSCI 151", Slug: demoSlug, Title: "Programming for Scientists and Engineers", Department: &dept,
	})
	if err != nil {
		return "", fmt.Errorf("create course: %w", err)
	}
	offering, err := q.CreateOffering(ctx, catalogdb.CreateOfferingParams{CourseID: course.ID, Year: 2025, Term: "fall"})
	if err != nil {
		return "", fmt.Errorf("create offering: %w", err)
	}
	one := int32(1)
	midterm, err := q.CreateAssessment(ctx, catalogdb.CreateAssessmentParams{OfferingID: offering.ID, Kind: "midterm", Number: &one})
	if err != nil {
		return "", fmt.Errorf("create assessment: %w", err)
	}
	material, err := q.CreateMaterial(ctx, catalogdb.CreateMaterialParams{
		OfferingID: offering.ID, AssessmentID: &midterm.ID,
		Title: "Midterm 1 questions (demo)", Type: "questions", Description: "Demo page generated by cmd/seed",
	})
	if err != nil {
		return "", fmt.Errorf("create material: %w", err)
	}

	// The file id is generated here because it is part of the key (R-ST-2).
	fileID := uuid.New()
	key := fmt.Sprintf("materials/%s/%s.png", material.ID, fileID)
	sum := sha256.Sum256(page)
	if _, err := q.CreateMaterialFile(ctx, catalogdb.CreateMaterialFileParams{
		ID: fileID, MaterialID: material.ID, StorageKey: key, MimeType: "image/png",
		SizeBytes: int64(len(page)), Sha256: hex.EncodeToString(sum[:]), Position: 0,
	}); err != nil {
		return "", fmt.Errorf("create material file: %w", err)
	}
	return key, nil
}

// demoPNG draws a 400×200 blue rectangle so there's something to preview.
func demoPNG() ([]byte, error) {
	const width, height = 400, 200
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	blue := color.RGBA{R: 30, G: 64, B: 175, A: 255}
	for y := range height {
		for x := range width {
			img.Set(x, y, blue)
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		return nil, fmt.Errorf("encode demo png: %w", err)
	}
	return buf.Bytes(), nil
}
