// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package catalogdb

import (
	"time"

	"github.com/google/uuid"
)

type Assessment struct {
	ID         uuid.UUID
	OfferingID uuid.UUID
	Kind       string
	Number     *int32
	Label      *string
	CreatedAt  time.Time
}

type Course struct {
	ID         uuid.UUID
	Code       string
	Slug       string
	Title      string
	Department *string
	CreatedAt  time.Time
}

type Material struct {
	ID           uuid.UUID
	OfferingID   uuid.UUID
	AssessmentID *uuid.UUID
	Title        string
	Type         string
	Description  string
	PublishedAt  time.Time
	HiddenAt     *time.Time
}

type MaterialFile struct {
	ID         uuid.UUID
	MaterialID uuid.UUID
	StorageKey string
	MimeType   string
	SizeBytes  int64
	Sha256     string
	Position   int32
}

type Offering struct {
	ID         uuid.UUID
	CourseID   uuid.UUID
	Year       int32
	Term       string
	Instructor *string
	CreatedAt  time.Time
}
