// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package catalogdb

import (
	"context"

	"github.com/google/uuid"
)

const countCourses = `-- name: CountCourses :one
SELECT count(*) FROM courses
WHERE $1::text = ''
   OR code  ILIKE '%' || $1::text || '%'
   OR title ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountCourses(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments (offering_id, kind, number, label)
VALUES ($1, $2, $3, $4)
RETURNING id, offering_id, kind, number, label, created_at
`

type CreateAssessmentParams struct {
	OfferingID uuid.UUID
	Kind       string
	Number     *int32
	Label      *string
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.OfferingID,
		arg.Kind,
		arg.Number,
		arg.Label,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.OfferingID,
		&i.Kind,
		&i.Number,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one

INSERT INTO courses (code, slug, title, department)
VALUES ($1, $2, $3, $4)
RETURNING id, code, slug, title, department, created_at
`

type CreateCourseParams struct {
	Code       string
	Slug       string
	Title      string
	Department *string
}

// The Create* queries are used by the seed command and tests now, and by the
// moderation "approve" flow in Plan 5.
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Code,
		arg.Slug,
		arg.Title,
		arg.Department,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Title,
		&i.Department,
		&i.CreatedAt,
	)
	return i, err
}

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (offering_id, assessment_id, title, type, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, offering_id, assessment_id, title, type, description, published_at, hidden_at
`

type CreateMaterialParams struct {
	OfferingID   uuid.UUID
	AssessmentID *uuid.UUID
	Title        string
	Type         string
	Description  string
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.OfferingID,
		arg.AssessmentID,
		arg.Title,
		arg.Type,
		arg.Description,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.OfferingID,
		&i.AssessmentID,
		&i.Title,
		&i.Type,
		&i.Description,
		&i.PublishedAt,
		&i.HiddenAt,
	)
	return i, err
}

const createMaterialFile = `-- name: CreateMaterialFile :one
INSERT INTO material_files (id, material_id, storage_key, mime_type, size_bytes, sha256, position)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, material_id, storage_key, mime_type, size_bytes, sha256, position
`

type CreateMaterialFileParams struct {
	ID         uuid.UUID
	MaterialID uuid.UUID
	StorageKey string
	MimeType   string
	SizeBytes  int64
	Sha256     string
	Position   int32
}

// The id is supplied by the caller because it is part of storage_key (R-DB-15).
func (q *Queries) CreateMaterialFile(ctx context.Context, arg CreateMaterialFileParams) (MaterialFile, error) {
	row := q.db.QueryRow(ctx, createMaterialFile,
		arg.ID,
		arg.MaterialID,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256,
		arg.Position,
	)
	var i MaterialFile
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Position,
	)
	return i, err
}

const createOffering = `-- name: CreateOffering :one
INSERT INTO offerings (course_id, year, term, instructor)
VALUES ($1, $2, $3, $4)
RETURNING id, course_id, year, term, instructor, created_at
`

type CreateOfferingParams struct {
	CourseID   uuid.UUID
	Year       int32
	Term       string
	Instructor *string
}

func (q *Queries) CreateOffering(ctx context.Context, arg CreateOfferingParams) (Offering, error) {
	row := q.db.QueryRow(ctx, createOffering,
		arg.CourseID,
		arg.Year,
		arg.Term,
		arg.Instructor,
	)
	var i Offering
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Year,
		&i.Term,
		&i.Instructor,
		&i.CreatedAt,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, code, slug, title, department, created_at FROM courses WHERE slug = $1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Slug,
		&i.Title,
		&i.Department,
		&i.CreatedAt,
	)
	return i, err
}

const getMaterialContext = `-- name: GetMaterialContext :one
SELECT c.id    AS course_id,
       c.code  AS course_code,
       c.slug  AS course_slug,
       c.title AS course_title,
       o.id    AS offering_id,
       o.year  AS offering_year,
       o.term  AS offering_term,
       o.instructor AS offering_instructor,
       a.id     AS assessment_id,
       a.kind   AS assessment_kind,
       a.number AS assessment_number,
       a.label  AS assessment_label
FROM materials m
JOIN offerings o ON o.id = m.offering_id
JOIN courses c   ON c.id = o.course_id
LEFT JOIN assessments a ON a.id = m.assessment_id
WHERE m.id = $1
`

type GetMaterialContextRow struct {
	CourseID           uuid.UUID
	CourseCode         string
	CourseSlug         string
	CourseTitle        string
	OfferingID         uuid.UUID
	OfferingYear       int32
	OfferingTerm       string
	OfferingInstructor *string
	AssessmentID       *uuid.UUID
	AssessmentKind     *string
	AssessmentNumber   *int32
	AssessmentLabel    *string
}

// The course / offering / assessment a material belongs to, so the material
// page can show "CSCI 151 · 2025 Fall · Midterm 1" (R-EP-15). Assessment
// columns come from a LEFT JOIN and are therefore nullable.
func (q *Queries) GetMaterialContext(ctx context.Context, id uuid.UUID) (GetMaterialContextRow, error) {
	row := q.db.QueryRow(ctx, getMaterialContext, id)
	var i GetMaterialContextRow
	err := row.Scan(
		&i.CourseID,
		&i.CourseCode,
		&i.CourseSlug,
		&i.CourseTitle,
		&i.OfferingID,
		&i.OfferingYear,
		&i.OfferingTerm,
		&i.OfferingInstructor,
		&i.AssessmentID,
		&i.AssessmentKind,
		&i.AssessmentNumber,
		&i.AssessmentLabel,
	)
	return i, err
}

const getOffering = `-- name: GetOffering :one
SELECT id, course_id, year, term, instructor, created_at FROM offerings WHERE id = $1
`

func (q *Queries) GetOffering(ctx context.Context, id uuid.UUID) (Offering, error) {
	row := q.db.QueryRow(ctx, getOffering, id)
	var i Offering
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Year,
		&i.Term,
		&i.Instructor,
		&i.CreatedAt,
	)
	return i, err
}

const getVisibleMaterial = `-- name: GetVisibleMaterial :one
SELECT id, offering_id, assessment_id, title, type, description, published_at, hidden_at FROM materials WHERE id = $1 AND hidden_at IS NULL
`

func (q *Queries) GetVisibleMaterial(ctx context.Context, id uuid.UUID) (Material, error) {
	row := q.db.QueryRow(ctx, getVisibleMaterial, id)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.OfferingID,
		&i.AssessmentID,
		&i.Title,
		&i.Type,
		&i.Description,
		&i.PublishedAt,
		&i.HiddenAt,
	)
	return i, err
}

const getVisibleMaterialFile = `-- name: GetVisibleMaterialFile :one
SELECT f.id,
       f.storage_key,
       f.mime_type,
       f.sha256,
       f.position,
       m.title AS material_title,
       c.slug  AS course_slug
FROM material_files f
JOIN materials m ON m.id = f.material_id
JOIN offerings o ON o.id = m.offering_id
JOIN courses c   ON c.id = o.course_id
WHERE f.id = $1 AND m.hidden_at IS NULL
`

type GetVisibleMaterialFileRow struct {
	ID            uuid.UUID
	StorageKey    string
	MimeType      string
	Sha256        string
	Position      int32
	MaterialTitle string
	CourseSlug    string
}

// Joins up to the material (for visibility) and the course (for a readable
// download filename). A file of a hidden material is simply "not found".
func (q *Queries) GetVisibleMaterialFile(ctx context.Context, id uuid.UUID) (GetVisibleMaterialFileRow, error) {
	row := q.db.QueryRow(ctx, getVisibleMaterialFile, id)
	var i GetVisibleMaterialFileRow
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.MimeType,
		&i.Sha256,
		&i.Position,
		&i.MaterialTitle,
		&i.CourseSlug,
	)
	return i, err
}

const listAssessmentsByCourse = `-- name: ListAssessmentsByCourse :many
SELECT id, offering_id, kind, number, label, created_at FROM assessments
WHERE offering_id IN (SELECT o.id FROM offerings o WHERE o.course_id = $1)
ORDER BY offering_id,
         CASE kind WHEN 'quiz' THEN 1 WHEN 'midterm' THEN 2 WHEN 'final' THEN 3
                   WHEN 'assignment' THEN 4 WHEN 'lab' THEN 5 ELSE 6 END,
         number NULLS LAST,
         label NULLS LAST,
         id
`

// All assessments of all offerings of a course in one query (instead of one
// query per offering, the classic "N+1" problem). Go groups them afterwards.
func (q *Queries) ListAssessmentsByCourse(ctx context.Context, courseID uuid.UUID) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, listAssessmentsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.OfferingID,
			&i.Kind,
			&i.Number,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialFiles = `-- name: ListMaterialFiles :many
SELECT id, material_id, storage_key, mime_type, size_bytes, sha256, position FROM material_files WHERE material_id = $1 ORDER BY position
`

func (q *Queries) ListMaterialFiles(ctx context.Context, materialID uuid.UUID) ([]MaterialFile, error) {
	rows, err := q.db.Query(ctx, listMaterialFiles, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaterialFile
	for rows.Next() {
		var i MaterialFile
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.StorageKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferingsByCourse = `-- name: ListOfferingsByCourse :many
SELECT id, course_id, year, term, instructor, created_at FROM offerings
WHERE course_id = $1
ORDER BY year DESC,
         CASE term WHEN 'fall' THEN 1 WHEN 'summer' THEN 2 ELSE 3 END,
         instructor NULLS LAST,
         id
`

// Newest first; within a year fall → summer → spring (R-EP-8).
func (q *Queries) ListOfferingsByCourse(ctx context.Context, courseID uuid.UUID) ([]Offering, error) {
	rows, err := q.db.Query(ctx, listOfferingsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offering
	for rows.Next() {
		var i Offering
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Year,
			&i.Term,
			&i.Instructor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleMaterialsByOffering = `-- name: ListVisibleMaterialsByOffering :many
SELECT m.id, m.offering_id, m.assessment_id, m.title, m.type, m.description, m.published_at, m.hidden_at
FROM materials m
LEFT JOIN assessments a ON a.id = m.assessment_id
WHERE m.offering_id = $1 AND m.hidden_at IS NULL
ORDER BY (m.assessment_id IS NOT NULL),
         CASE a.kind WHEN 'quiz' THEN 1 WHEN 'midterm' THEN 2 WHEN 'final' THEN 3
                     WHEN 'assignment' THEN 4 WHEN 'lab' THEN 5 ELSE 6 END,
         a.number NULLS LAST,
         a.label NULLS LAST,
         a.id,
         m.type,
         m.title,
         m.id
`

// General materials (no assessment) first, then in assessment order (R-EP-14).
// The LEFT JOIN is only used for sorting; we still return material columns.
func (q *Queries) ListVisibleMaterialsByOffering(ctx context.Context, offeringID uuid.UUID) ([]Material, error) {
	rows, err := q.db.Query(ctx, listVisibleMaterialsByOffering, offeringID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.OfferingID,
			&i.AssessmentID,
			&i.Title,
			&i.Type,
			&i.Description,
			&i.PublishedAt,
			&i.HiddenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCourses = `-- name: SearchCourses :many

SELECT id, code, slug, title, department, created_at FROM courses
WHERE $1::text = ''
   OR code  ILIKE '%' || $1::text || '%'
   OR title ILIKE '%' || $1::text || '%'
ORDER BY code, id
LIMIT $3 OFFSET $2
`

type SearchCoursesParams struct {
	Query     string
	RowOffset int32
	RowLimit  int32
}

// Queries for the public catalog. sqlc turns each "-- name: X :kind" block
// into a Go method X on catalogdb.Queries:
//
//	:one  → returns a single row (pgx.ErrNoRows if none)
//	:many → returns a slice
//
// Every list ends its ORDER BY with "id" so that ties are broken the same way
// every time; without it PostgreSQL may return equal rows in any order and
// pagination could skip or repeat rows.
//
// Public queries over materials filter "hidden_at IS NULL" (spec R-API-20).
// sqlc.arg(query) must already be LIKE-escaped by the caller (\ % _ prefixed
// with a backslash), so user input is matched literally. ” matches all.
func (q *Queries) SearchCourses(ctx context.Context, arg SearchCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, searchCourses, arg.Query, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Slug,
			&i.Title,
			&i.Department,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
