-- Catalog schema: course → offering → assessment → material → material file.
-- Requirement ids (R-DB-*) refer to docs/superpowers/specs/2026-10-07-plan-1-catalog-api-spec.md.
--
-- Conventions used throughout:
--   * Primary keys are UUIDs generated by PostgreSQL (gen_random_uuid() is
--     built in since PG 13). UUIDs don't leak row counts and can be created
--     by the application before inserting (see material_files.id).
--   * "Enums" are text + CHECK rather than PostgreSQL ENUM types: adding a
--     value later is a one-line migration, and sqlc maps them to plain Go strings.
--   * Optional text columns must be NULL or non-empty, so "missing" has exactly
--     one representation (NULL), never also ''.

-- +goose Up

CREATE TABLE courses (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    code        text NOT NULL CHECK (length(code) BETWEEN 1 AND 32),
    -- URL-safe identifier, e.g. "csci-151" (R-DB-2).
    slug        text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    title       text NOT NULL CHECK (length(title) BETWEEN 1 AND 200),
    department  text CHECK (department <> ''),
    created_at  timestamptz NOT NULL DEFAULT now()
);
-- An expression index makes the code unique case-insensitively (R-DB-1):
-- "CSCI 151" and "csci 151" collide. upper() is Unicode-aware thanks to the
-- builtin C.UTF-8 locale the database is created with (R-DB-0).
CREATE UNIQUE INDEX courses_code_ci_key ON courses (upper(code));

CREATE TABLE offerings (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id   uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    year        int  NOT NULL CHECK (year BETWEEN 2000 AND 2100),
    term        text NOT NULL CHECK (term IN ('spring', 'summer', 'fall')),
    instructor  text CHECK (instructor <> ''),
    created_at  timestamptz NOT NULL DEFAULT now(),
    -- By default SQL treats NULLs as all different, so two "2025 fall, no
    -- instructor" rows would both be allowed. NULLS NOT DISTINCT (PG 15+)
    -- makes them collide, which is what a human would expect (R-DB-7).
    -- The index also covers lookups by course_id, so no separate index is needed.
    CONSTRAINT offerings_natural_key UNIQUE NULLS NOT DISTINCT (course_id, year, term, instructor)
);

CREATE TABLE assessments (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    offering_id  uuid NOT NULL REFERENCES offerings (id) ON DELETE CASCADE,
    kind         text NOT NULL CHECK (kind IN ('midterm', 'quiz', 'final', 'assignment', 'lab', 'other')),
    number       int  CHECK (number > 0),
    label        text CHECK (label <> ''),
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT assessments_natural_key UNIQUE NULLS NOT DISTINCT (offering_id, kind, number, label),
    -- (offering_id, id) is trivially unique because id already is, but a
    -- composite foreign key needs a matching unique constraint to point at.
    CONSTRAINT assessments_offering_id_id_key UNIQUE (offering_id, id)
);

CREATE TABLE materials (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    offering_id    uuid NOT NULL REFERENCES offerings (id) ON DELETE CASCADE,
    assessment_id  uuid,
    title          text NOT NULL CHECK (length(title) BETWEEN 1 AND 200),
    type           text NOT NULL CHECK (type IN ('questions', 'solutions', 'notes', 'slides', 'cheatsheet', 'other')),
    description    text NOT NULL DEFAULT '',
    published_at   timestamptz NOT NULL DEFAULT now(),
    -- NULL = visible. Moderators set it to hide a material (Plan 5); every
    -- public query filters on it (R-DB-14, R-API-20).
    hidden_at      timestamptz,
    -- Composite FK (R-DB-12): the pair (offering_id, assessment_id) must exist
    -- in assessments, so a material can only point at an assessment of ITS OWN
    -- offering. When assessment_id is NULL the FK is not checked (MATCH SIMPLE).
    -- "SET NULL (assessment_id)" (PG 15+) clears only assessment_id when the
    -- assessment is deleted; plain SET NULL would also null offering_id, which
    -- is NOT NULL and would make the delete fail.
    CONSTRAINT materials_assessment_fkey
        FOREIGN KEY (offering_id, assessment_id)
        REFERENCES assessments (offering_id, id)
        ON DELETE SET NULL (assessment_id)
);
CREATE INDEX materials_offering_idx ON materials (offering_id);
CREATE INDEX materials_assessment_idx ON materials (assessment_id);

CREATE TABLE material_files (
    -- The default exists for convenience, but the application normally
    -- generates the id itself because it is part of storage_key (R-DB-15).
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    material_id  uuid NOT NULL REFERENCES materials (id) ON DELETE CASCADE,
    -- Approved files always live under materials/ (R-DB-16). The public file
    -- endpoint reads keys from this table only, so it can never be tricked
    -- into serving a pending (unmoderated) upload.
    storage_key  text NOT NULL UNIQUE CHECK (storage_key ~ '^materials/'),
    -- Allow-list (R-DB-17). The value is echoed as Content-Type when the file
    -- is served, so text/html or image/svg+xml here would let an uploaded file
    -- run JavaScript on our domain (stored XSS). The database refuses them.
    mime_type    text NOT NULL CHECK (mime_type IN (
        'application/pdf',
        'image/png',
        'image/jpeg',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    )),
    size_bytes   bigint NOT NULL CHECK (size_bytes > 0),
    -- Lower-case hex SHA-256 of the content: used for duplicate detection and
    -- as the HTTP ETag (R-DB-18, R-EP-18).
    sha256       text NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    -- Page order within the material, starting at 0.
    position     int  NOT NULL CHECK (position >= 0),
    CONSTRAINT material_files_position_key UNIQUE (material_id, position)
);

-- +goose Down
-- Drop in reverse dependency order (children before parents).
DROP TABLE material_files;
DROP TABLE materials;
DROP TABLE assessments;
DROP TABLE offerings;
DROP TABLE courses;
